'use client'
import { client } from '@/api/apollo.interceptor'
import Navbar from '@/components/navbar/Navbar'
import PlayerWrapper from '@/components/player/PlayerWrapper'
import ToasterProvider from '@/providers/toaster-provider/ToasterProvider'
import { persistor, store } from '@/store/store'
import { ApolloProvider } from '@apollo/client'
import { loadDevMessages, loadErrorMessages } from '@apollo/client/dev'
import { NextUIProvider } from '@nextui-org/react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { Roboto } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { PropsWithChildren } from 'react'
import { Provider } from 'react-redux'
import { PersistGate } from 'redux-persist/integration/react'
import './globals.css'

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
    },
  },
})
export default function RootLayout({ children }: PropsWithChildren<unknown>) {
  const pathname = usePathname()

  loadDevMessages()
  loadErrorMessages()
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ApolloProvider client={client}>
          <NextUIProvider>
            <QueryClientProvider client={queryClient}>
              <Provider store={store}>
                <PersistGate persistor={persistor} loading={null}>
                  <ToasterProvider />
                  <div>
                    {pathname.includes('auth') ||
                    pathname.includes('account') ||
                    pathname.includes('admin') ? (
                      <div>{children}</div>
                    ) : (
                      <div className="grid overflow-hidden grid-cols-[0.1fr,1fr] grid-rows-1 gap-x-0 gap-y-0">
                        <Navbar />
                        <div className="p-2 pl-0">{children}</div>
                        <PlayerWrapper />
                      </div>
                    )}
                  </div>
                </PersistGate>
              </Provider>
            </QueryClientProvider>
          </NextUIProvider>
        </ApolloProvider>
        <div id="modal"></div>
      </body>
    </html>
  )
}
