'use client'
import { client } from '@/api/apollo.config'
import Navbar from '@/components/navbar/Navbar'
import PlayerWrapper from '@/components/player/PlayerWrapper'
import AuthProvider from '@/providers/auth-provider/AuthProvider'
import ToasterProvider from '@/providers/toaster-provider/ToasterProvider'
import { ApolloProvider } from '@apollo/client'
import { loadDevMessages, loadErrorMessages } from '@apollo/client/dev'
import { NextUIProvider } from '@nextui-org/react'
import { Roboto } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { PropsWithChildren } from 'react'
import './globals.css'

const roboto = Roboto({
  weight: ['400', '500', '700', '900'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: PropsWithChildren<unknown>) {
  const pathname = usePathname()

  loadDevMessages()
  loadErrorMessages()
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ApolloProvider client={client}>
          <AuthProvider>
            <NextUIProvider>
              <ToasterProvider />
              <>
                {pathname.includes('auth') ||
                pathname.includes('account') ||
                pathname.includes('admin') ? (
                  <div>{children}</div>
                ) : (
                  <div className="main-container">
                    <Navbar />
                    <div className="main-page">{children}</div>
                    <PlayerWrapper />
                  </div>
                )}
              </>
            </NextUIProvider>
          </AuthProvider>
        </ApolloProvider>
      </body>
    </html>
  )
}
